### ISSUE TITLE
Referencing internal git repos for CCP documentation

### ISSUE THREAD

**Issue by mattkferguson** [CiscoDevNet/multicloud-integrations#8]
Thank you for filing an Issue. Please provide the following details to help us understand more about the issue.

This Issue is for :

- [ ] Feature
- [ ] Bug/Missing Information
- [ ] Typos/Grammatical Errors
- [*] Broken Links
- [ ] Others

**Problem**
The following Cisco Container Platform documentation url: https://github.com/CiscoDevNet/multicloud-integrations/blob/master/AWS/External/ccp.md references  internal Cisco git repos: https://wwwin-github.cisco.com/CPSG/ccp-docs/blob/master/install-docs/CCP-Installation-Guide-01.md#installing-cisco-container-platform-on-vsphere-web-client and https://wwwin-github.cisco.com/CPSG/ccp-docs/blob/master/install-docs/CCP-User-Guide-01.md#creating-kubernetes-clusters

**Proposed Solution**
Reference public facing documentation

**Found in...**

*Link to the document*

**Comment by byrneo** [comment]
Fixed :)

**Comment by byrneo** [comment]
Fixed :)
